### ISSUE TITLE
[BUG] How to inverse_transform (One-Hot) float number. + ValueError: Specifying the columns using strings is only supported for pandas DataFrames

### ISSUE THREAD

**Issue by lily860220** [ydataai/ydata-synthetic#65]
Hi, I am trying to run your code "adult_wgangp.py".

(1) Problem 1 : Bug
I have an error here "processed_data = pd.DataFrame.sparse.from_spmatrix(preprocessor.fit_transform(processed_data))" , 
and the error is "ValueError: Specifying the columns using strings is only supported for pandas DataFrames".
- Slove
I separate these two methods and got transformed dataframe. (One-Hot + Standard Scalar)

(2) Problem 2 : How to inverse_transform (One-Hot) float value.

I want to combine synthetic data with original minority class data, then I will feed the combined dataframe (balanced data = synthetic data +  original minority data) to model. 
But the code here note that it is not inverse processed.
After generation, data_sample is the generated data as below.
```
#Sampling the data
#Note that the data returned it is not inverse processed.
data_sample = synth.sample(100000)
```
After the transform processed, discrete data is converted to one-hot vector [0,0,1], and then generated by GAN, which will become [-0.009592 -0.128386 1.009473].
Because I want to combine synthetic data and original minority data, I have to inverse_transform synthetic data.
But for inverse_transform, the one hot value must be 0 or 1, not float value. (-0.009592 -0.128386 1.009473).
I don't know how to make the float value to 0 or 1 in discrete column.
I really don't know how to deal with it and search many methods, but I still can't solve it.
I am wandering if you write a notebook to let me know how to solve it ?

Thank you,
Lily

**Comment by fabclmnt** [comment]
Hi @lily860220,

The problem 1 is not a bug, it's an error message returned because the way the dataset was passed to the processing method was not as expected. In order for me to better help you, please provide all the source code you're using. This will provide me more detail. I suggest you to ask for support in our #help channel in the synthetic data community slack. 

the inverse transformation is the application of the inverse transformation from the methods applied in the initial data processing. By checking the code here https://github.com/ydataai/ydata-synthetic/blob/master/src/ydata_synthetic/preprocessing/regular/adult.py, you can easily perform the inverse transformations (MinMax scaler and Onehotencoding).

Feel free to reach me out through Slack.
